include: package:lint/analysis_options.yaml
analyzer:
  exclude:
    - "**/**.g.dart"
    - "**/**.freezed.dart"
    - "**.yaml"


linter:
  rules:
    sort_constructors_first: false
    constant_identifier_names: false
    always_put_required_named_parameters_first: false
    prefer_single_quotes: true